name: Build and deploy Node.js app to Azure Web App - app-monagenda-cyrmat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Upload build for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: . # or specify 
